version: '3'

services:
  block:
    build:
      context: .
      dockerfile: ./compose/local/block/Dockerfile
    image: docker.qabel.de/qabel-block-dev
    env_file:
      - ./.envs/.local/.block
      - ./.envs/.local/.postgres
    command: /start
